# Generated by Django 3.2.6 on 2021-09-05 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresosesion',
            name='preguntas_disponibles',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 7, 19, 55, 352989)),
        ),
        migrations.AlterField(
            model_name='partidasdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 7, 19, 55, 353245)),
        ),
    ]
